version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "Asia/Shanghai"

  - package-ecosystem: "cargo"
    directories:
      - "/aqara"
      - "/aqara-cli"
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "Asia/Shanghai"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "Asia/Shanghai"
